DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS UserGroup;
  
CREATE TABLE User (
  userId INT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  groupId VARCHAR(250) NOT NULL
);

CREATE TABLE Item (
  name VARCHAR(250) NOT NULL PRIMARY KEY,
  amount INT NOT NULL,
  paid_by VARCHAR(250) NOT NULL,
  split_by VARCHAR(250) NOT NULL
);


CREATE TABLE User (
  groupId INT PRIMARY KEY,
  groupName VARCHAR(250) NOT NULL,
);